name: Build and Push Image to Dockerhub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Change directory to webapp
        run: cd webapp
      - name: Build webapp
        run: docker build . -t matthisfoulonneau/not-a-qr-generator-webapp:latest
      - name: Change directory to server
        run: cd ../server
      - name: Build server
        run: docker build . -t matthisfoulonneau/not-a-qr-generator-api-server:latest
      - name: Push webapp
        run: docker push matthisfoulonneau/not-a-qr-generator-webapp:latest
      - name: Push server
        run: docker push matthisfoulonneau/not-a-qr-generator-api-server:latest
